### ISSUE TITLE
save_ply  binary saving   ERROR message

### ISSUE THREAD

**Issue by greensander** [FugroRoames/PlyIO.jl#16]
Good day.   
I am pretty new on graphics and digging in ply file format.    While I was trying saving in binary format (not ascii)  I got the following message, which I could not avoid.      I was testing PlyIO.jl  example script.  

julia>  save_ply(ply, "test.ply")  
Error:   MethodsError: no method matching Array{Float64,2}(::Int64, ::Int64)

Any clue related would be appreciated.   Have a good one.

**Comment by andyferris** [comment]
Wow - I guess we need a test case for that. :)

In Julia 1.x the method is `Matrix{Float64}(undef::UndefInitializer, n, m)`. We just need to add the `undef` part to whereever it is throwing the error (visibible in the stacktrace). If you are able to create a pull request it would be greatly appreciated.

**Comment by FilipJergleAlmquist** [comment]
Hello, I have created a pull request (#17) adding `undef` to the Matrix constructor.

**Comment by c42f** [comment]
Fix + tests are now available in release v1.1.1
